;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	awesome-pair-forward-delete
	awesome-pair-kill
	awesome-pair-space
	ivy-mouse-done
	))

(setq mc/cmds-to-run-once
      '(
	))
